// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/cloud_block_storage_backups.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/cloud_block_storage_backups_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/cloud_block_storage_backups.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudBlockStorageBackupsService is a mock of CloudBlockStorageBackupsService interface.
type MockCloudBlockStorageBackupsService struct {
	ctrl     *gomock.Controller
	recorder *MockCloudBlockStorageBackupsServiceMockRecorder
	isgomock struct{}
}

// MockCloudBlockStorageBackupsServiceMockRecorder is the mock recorder for MockCloudBlockStorageBackupsService.
type MockCloudBlockStorageBackupsServiceMockRecorder struct {
	mock *MockCloudBlockStorageBackupsService
}

// NewMockCloudBlockStorageBackupsService creates a new mock instance.
func NewMockCloudBlockStorageBackupsService(ctrl *gomock.Controller) *MockCloudBlockStorageBackupsService {
	mock := &MockCloudBlockStorageBackupsService{ctrl: ctrl}
	mock.recorder = &MockCloudBlockStorageBackupsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudBlockStorageBackupsService) EXPECT() *MockCloudBlockStorageBackupsServiceMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockCloudBlockStorageBackupsService) Collection() serverscom.Collection[serverscom.CloudBlockStorageBackup] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.CloudBlockStorageBackup])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockCloudBlockStorageBackupsServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockCloudBlockStorageBackupsService)(nil).Collection))
}

// Create mocks base method.
func (m *MockCloudBlockStorageBackupsService) Create(ctx context.Context, input serverscom.CloudBlockStorageBackupCreateInput) (*serverscom.CloudBlockStorageBackup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCloudBlockStorageBackupsServiceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCloudBlockStorageBackupsService)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockCloudBlockStorageBackupsService) Delete(ctx context.Context, id string) (*serverscom.CloudBlockStorageBackup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCloudBlockStorageBackupsServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCloudBlockStorageBackupsService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockCloudBlockStorageBackupsService) Get(ctx context.Context, id string) (*serverscom.CloudBlockStorageBackup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCloudBlockStorageBackupsServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCloudBlockStorageBackupsService)(nil).Get), ctx, id)
}

// Restore mocks base method.
func (m *MockCloudBlockStorageBackupsService) Restore(ctx context.Context, id string, input serverscom.CloudBlockStorageBackupRestoreInput) (*serverscom.CloudBlockStorageBackup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockCloudBlockStorageBackupsServiceMockRecorder) Restore(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockCloudBlockStorageBackupsService)(nil).Restore), ctx, id, input)
}

// Update mocks base method.
func (m *MockCloudBlockStorageBackupsService) Update(ctx context.Context, id string, input serverscom.CloudBlockStorageBackupUpdateInput) (*serverscom.CloudBlockStorageBackup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCloudBlockStorageBackupsServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCloudBlockStorageBackupsService)(nil).Update), ctx, id, input)
}
