// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/cloud_block_storage_volumes.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/cloud_block_storage_volumes_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/cloud_block_storage_volumes.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudBlockStorageVolumesService is a mock of CloudBlockStorageVolumesService interface.
type MockCloudBlockStorageVolumesService struct {
	ctrl     *gomock.Controller
	recorder *MockCloudBlockStorageVolumesServiceMockRecorder
	isgomock struct{}
}

// MockCloudBlockStorageVolumesServiceMockRecorder is the mock recorder for MockCloudBlockStorageVolumesService.
type MockCloudBlockStorageVolumesServiceMockRecorder struct {
	mock *MockCloudBlockStorageVolumesService
}

// NewMockCloudBlockStorageVolumesService creates a new mock instance.
func NewMockCloudBlockStorageVolumesService(ctrl *gomock.Controller) *MockCloudBlockStorageVolumesService {
	mock := &MockCloudBlockStorageVolumesService{ctrl: ctrl}
	mock.recorder = &MockCloudBlockStorageVolumesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudBlockStorageVolumesService) EXPECT() *MockCloudBlockStorageVolumesServiceMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockCloudBlockStorageVolumesService) Attach(ctx context.Context, id string, input serverscom.CloudBlockStorageVolumeAttachInput) (*serverscom.CloudBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Attach indicates an expected call of Attach.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Attach(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Attach), ctx, id, input)
}

// Collection mocks base method.
func (m *MockCloudBlockStorageVolumesService) Collection() serverscom.Collection[serverscom.CloudBlockStorageVolume] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.CloudBlockStorageVolume])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Collection))
}

// Create mocks base method.
func (m *MockCloudBlockStorageVolumesService) Create(ctx context.Context, input serverscom.CloudBlockStorageVolumeCreateInput) (*serverscom.CloudBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockCloudBlockStorageVolumesService) Delete(ctx context.Context, id string) (*serverscom.CloudBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Delete), ctx, id)
}

// Detach mocks base method.
func (m *MockCloudBlockStorageVolumesService) Detach(ctx context.Context, id string, input serverscom.CloudBlockStorageVolumeDetachInput) (*serverscom.CloudBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detach indicates an expected call of Detach.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Detach(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Detach), ctx, id, input)
}

// Get mocks base method.
func (m *MockCloudBlockStorageVolumesService) Get(ctx context.Context, id string) (*serverscom.CloudBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockCloudBlockStorageVolumesService) Update(ctx context.Context, id string, input serverscom.CloudBlockStorageVolumeUpdateInput) (*serverscom.CloudBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.CloudBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCloudBlockStorageVolumesServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCloudBlockStorageVolumesService)(nil).Update), ctx, id, input)
}
