// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/cloud_computing_regions.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/cloud_computing_regions_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/cloud_computing_regions.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudComputingRegionsService is a mock of CloudComputingRegionsService interface.
type MockCloudComputingRegionsService struct {
	ctrl     *gomock.Controller
	recorder *MockCloudComputingRegionsServiceMockRecorder
	isgomock struct{}
}

// MockCloudComputingRegionsServiceMockRecorder is the mock recorder for MockCloudComputingRegionsService.
type MockCloudComputingRegionsServiceMockRecorder struct {
	mock *MockCloudComputingRegionsService
}

// NewMockCloudComputingRegionsService creates a new mock instance.
func NewMockCloudComputingRegionsService(ctrl *gomock.Controller) *MockCloudComputingRegionsService {
	mock := &MockCloudComputingRegionsService{ctrl: ctrl}
	mock.recorder = &MockCloudComputingRegionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudComputingRegionsService) EXPECT() *MockCloudComputingRegionsServiceMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockCloudComputingRegionsService) Collection() serverscom.Collection[serverscom.CloudComputingRegion] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.CloudComputingRegion])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockCloudComputingRegionsServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).Collection))
}

// CreateSnapshot mocks base method.
func (m *MockCloudComputingRegionsService) CreateSnapshot(ctx context.Context, regionID int64, input serverscom.CloudSnapshotCreateInput) (*serverscom.CloudSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, regionID, input)
	ret0, _ := ret[0].(*serverscom.CloudSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockCloudComputingRegionsServiceMockRecorder) CreateSnapshot(ctx, regionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).CreateSnapshot), ctx, regionID, input)
}

// Credentials mocks base method.
func (m *MockCloudComputingRegionsService) Credentials(ctx context.Context, regionID int64) (*serverscom.CloudComputingRegionCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credentials", ctx, regionID)
	ret0, _ := ret[0].(*serverscom.CloudComputingRegionCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Credentials indicates an expected call of Credentials.
func (mr *MockCloudComputingRegionsServiceMockRecorder) Credentials(ctx, regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credentials", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).Credentials), ctx, regionID)
}

// DeleteSnapshot mocks base method.
func (m *MockCloudComputingRegionsService) DeleteSnapshot(ctx context.Context, regionID int64, snapshotID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", ctx, regionID, snapshotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockCloudComputingRegionsServiceMockRecorder) DeleteSnapshot(ctx, regionID, snapshotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).DeleteSnapshot), ctx, regionID, snapshotID)
}

// Flavors mocks base method.
func (m *MockCloudComputingRegionsService) Flavors(regionID int64) serverscom.Collection[serverscom.CloudComputingFlavor] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flavors", regionID)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.CloudComputingFlavor])
	return ret0
}

// Flavors indicates an expected call of Flavors.
func (mr *MockCloudComputingRegionsServiceMockRecorder) Flavors(regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flavors", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).Flavors), regionID)
}

// Images mocks base method.
func (m *MockCloudComputingRegionsService) Images(regionID int64) serverscom.Collection[serverscom.CloudComputingImage] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Images", regionID)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.CloudComputingImage])
	return ret0
}

// Images indicates an expected call of Images.
func (mr *MockCloudComputingRegionsServiceMockRecorder) Images(regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Images", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).Images), regionID)
}

// Snapshots mocks base method.
func (m *MockCloudComputingRegionsService) Snapshots(regionID int64) serverscom.Collection[serverscom.CloudSnapshot] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshots", regionID)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.CloudSnapshot])
	return ret0
}

// Snapshots indicates an expected call of Snapshots.
func (mr *MockCloudComputingRegionsServiceMockRecorder) Snapshots(regionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshots", reflect.TypeOf((*MockCloudComputingRegionsService)(nil).Snapshots), regionID)
}
