// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/dns.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/dns_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/dns.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockDNSService is a mock of DNSService interface.
type MockDNSService struct {
	ctrl     *gomock.Controller
	recorder *MockDNSServiceMockRecorder
	isgomock struct{}
}

// MockDNSServiceMockRecorder is the mock recorder for MockDNSService.
type MockDNSServiceMockRecorder struct {
	mock *MockDNSService
}

// NewMockDNSService creates a new mock instance.
func NewMockDNSService(ctrl *gomock.Controller) *MockDNSService {
	mock := &MockDNSService{ctrl: ctrl}
	mock.recorder = &MockDNSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSService) EXPECT() *MockDNSServiceMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockDNSService) Collection() serverscom.Collection[serverscom.DNSDomain] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.DNSDomain])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockDNSServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockDNSService)(nil).Collection))
}

// CreateDomain mocks base method.
func (m *MockDNSService) CreateDomain(ctx context.Context, input serverscom.DNSDomainCreateInput) (*serverscom.DNSDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDomain", ctx, input)
	ret0, _ := ret[0].(*serverscom.DNSDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDomain indicates an expected call of CreateDomain.
func (mr *MockDNSServiceMockRecorder) CreateDomain(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDomain", reflect.TypeOf((*MockDNSService)(nil).CreateDomain), ctx, input)
}

// CreateRecord mocks base method.
func (m *MockDNSService) CreateRecord(ctx context.Context, domainID string, input serverscom.DNSRecordCreateInput) (*serverscom.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecord", ctx, domainID, input)
	ret0, _ := ret[0].(*serverscom.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecord indicates an expected call of CreateRecord.
func (mr *MockDNSServiceMockRecorder) CreateRecord(ctx, domainID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecord", reflect.TypeOf((*MockDNSService)(nil).CreateRecord), ctx, domainID, input)
}

// DeleteDomain mocks base method.
func (m *MockDNSService) DeleteDomain(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDomain", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDomain indicates an expected call of DeleteDomain.
func (mr *MockDNSServiceMockRecorder) DeleteDomain(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDomain", reflect.TypeOf((*MockDNSService)(nil).DeleteDomain), ctx, id)
}

// DeleteRecord mocks base method.
func (m *MockDNSService) DeleteRecord(ctx context.Context, domainID, recordID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", ctx, domainID, recordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockDNSServiceMockRecorder) DeleteRecord(ctx, domainID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockDNSService)(nil).DeleteRecord), ctx, domainID, recordID)
}

// GetDelegationData mocks base method.
func (m *MockDNSService) GetDelegationData(ctx context.Context) (*serverscom.DNSDomainDelegationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDelegationData", ctx)
	ret0, _ := ret[0].(*serverscom.DNSDomainDelegationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDelegationData indicates an expected call of GetDelegationData.
func (mr *MockDNSServiceMockRecorder) GetDelegationData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDelegationData", reflect.TypeOf((*MockDNSService)(nil).GetDelegationData), ctx)
}

// GetDomain mocks base method.
func (m *MockDNSService) GetDomain(ctx context.Context, id string) (*serverscom.DNSDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain", ctx, id)
	ret0, _ := ret[0].(*serverscom.DNSDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockDNSServiceMockRecorder) GetDomain(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockDNSService)(nil).GetDomain), ctx, id)
}

// GetRecord mocks base method.
func (m *MockDNSService) GetRecord(ctx context.Context, domainID, recordID string) (*serverscom.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", ctx, domainID, recordID)
	ret0, _ := ret[0].(*serverscom.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockDNSServiceMockRecorder) GetRecord(ctx, domainID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockDNSService)(nil).GetRecord), ctx, domainID, recordID)
}

// Records mocks base method.
func (m *MockDNSService) Records(domainID string) serverscom.Collection[serverscom.DNSRecord] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Records", domainID)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.DNSRecord])
	return ret0
}

// Records indicates an expected call of Records.
func (mr *MockDNSServiceMockRecorder) Records(domainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Records", reflect.TypeOf((*MockDNSService)(nil).Records), domainID)
}

// UpdateDomain mocks base method.
func (m *MockDNSService) UpdateDomain(ctx context.Context, id string, input serverscom.DNSDomainUpdateInput) (*serverscom.DNSDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDomain", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.DNSDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDomain indicates an expected call of UpdateDomain.
func (mr *MockDNSServiceMockRecorder) UpdateDomain(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomain", reflect.TypeOf((*MockDNSService)(nil).UpdateDomain), ctx, id, input)
}

// UpdateRecord mocks base method.
func (m *MockDNSService) UpdateRecord(ctx context.Context, domainID, recordID string, input serverscom.DNSRecordUpdateInput) (*serverscom.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecord", ctx, domainID, recordID, input)
	ret0, _ := ret[0].(*serverscom.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecord indicates an expected call of UpdateRecord.
func (mr *MockDNSServiceMockRecorder) UpdateRecord(ctx, domainID, recordID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecord", reflect.TypeOf((*MockDNSService)(nil).UpdateRecord), ctx, domainID, recordID, input)
}
