// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/racks.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/racks_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/racks.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockRacksService is a mock of RacksService interface.
type MockRacksService struct {
	ctrl     *gomock.Controller
	recorder *MockRacksServiceMockRecorder
	isgomock struct{}
}

// MockRacksServiceMockRecorder is the mock recorder for MockRacksService.
type MockRacksServiceMockRecorder struct {
	mock *MockRacksService
}

// NewMockRacksService creates a new mock instance.
func NewMockRacksService(ctrl *gomock.Controller) *MockRacksService {
	mock := &MockRacksService{ctrl: ctrl}
	mock.recorder = &MockRacksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRacksService) EXPECT() *MockRacksServiceMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockRacksService) Collection() serverscom.Collection[serverscom.Rack] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.Rack])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockRacksServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockRacksService)(nil).Collection))
}

// Get mocks base method.
func (m *MockRacksService) Get(ctx context.Context, id string) (*serverscom.Rack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*serverscom.Rack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRacksServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRacksService)(nil).Get), ctx, id)
}

// Update mocks base method.
func (m *MockRacksService) Update(ctx context.Context, id string, input serverscom.RackUpdateInput) (*serverscom.Rack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.Rack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRacksServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRacksService)(nil).Update), ctx, id, input)
}
