// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/remote_block_storage_volumes.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/mocks/rbs_volumes_service.go --package=mocks --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/remote_block_storage_volumes.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockRemoteBlockStorageVolumesService is a mock of RemoteBlockStorageVolumesService interface.
type MockRemoteBlockStorageVolumesService struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteBlockStorageVolumesServiceMockRecorder
	isgomock struct{}
}

// MockRemoteBlockStorageVolumesServiceMockRecorder is the mock recorder for MockRemoteBlockStorageVolumesService.
type MockRemoteBlockStorageVolumesServiceMockRecorder struct {
	mock *MockRemoteBlockStorageVolumesService
}

// NewMockRemoteBlockStorageVolumesService creates a new mock instance.
func NewMockRemoteBlockStorageVolumesService(ctrl *gomock.Controller) *MockRemoteBlockStorageVolumesService {
	mock := &MockRemoteBlockStorageVolumesService{ctrl: ctrl}
	mock.recorder = &MockRemoteBlockStorageVolumesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteBlockStorageVolumesService) EXPECT() *MockRemoteBlockStorageVolumesServiceMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockRemoteBlockStorageVolumesService) Collection() serverscom.Collection[serverscom.RemoteBlockStorageVolume] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.RemoteBlockStorageVolume])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).Collection))
}

// Create mocks base method.
func (m *MockRemoteBlockStorageVolumesService) Create(ctx context.Context, input serverscom.RemoteBlockStorageVolumeCreateInput) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockRemoteBlockStorageVolumesService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockRemoteBlockStorageVolumesService) Get(ctx context.Context, id string) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).Get), ctx, id)
}

// GetCredentials mocks base method.
func (m *MockRemoteBlockStorageVolumesService) GetCredentials(ctx context.Context, id string) (*serverscom.RemoteBlockStorageVolumeCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, id)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolumeCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) GetCredentials(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).GetCredentials), ctx, id)
}

// ResetCredentials mocks base method.
func (m *MockRemoteBlockStorageVolumesService) ResetCredentials(ctx context.Context, id string) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetCredentials", ctx, id)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetCredentials indicates an expected call of ResetCredentials.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) ResetCredentials(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetCredentials", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).ResetCredentials), ctx, id)
}

// Update mocks base method.
func (m *MockRemoteBlockStorageVolumesService) Update(ctx context.Context, id string, input serverscom.RemoteBlockStorageVolumeUpdateInput) (*serverscom.RemoteBlockStorageVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.RemoteBlockStorageVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRemoteBlockStorageVolumesServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRemoteBlockStorageVolumesService)(nil).Update), ctx, id, input)
}
