version: 2
before:
  hooks:
    - go mod tidy
    - go run cmd/gendoc/main.go
    - mkdir -p /tmp/srvctl-docs
    - zip -r /tmp/srvctl-docs/srvctl-docs-generated_{{ .Version }}.zip docs/generated

builds:
  - binary: srvctl
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - "ghcr.io/serverscom/{{ .ProjectName }}"
    tags:
      - "{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

archives:
  - formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  extra_files:
    - glob: /tmp/srvctl-docs/srvctl-docs-generated_*.zip
