version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: srvctl
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-amd64"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-arm64"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-amd64"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ if not .IsSnapshot }}v{{ end }}{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest-arm64"

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
