version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: srvctl
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256